import type { FieldConfig } from '@ghxstship/ui';
import { type MarketplaceListing } from './types';

export const LISTING_FIELD_CONFIGS: FieldConfig<MarketplaceListing>[] = [
  {
    key: 'title',
    label: 'Title',
    type: 'text',
    required: true,
    sortable: true,
    filterable: true,
  },
  {
    key: 'type',
    label: 'Type',
    type: 'select',
    required: true,
    sortable: true,
    filterable: true,
    options: [
      { label: 'Offer', value: 'offer' },
      { label: 'Request', value: 'request' },
      { label: 'Exchange', value: 'exchange' },
    ],
  },
  {
    key: 'category',
    label: 'Category',
    type: 'select',
    required: true,
    sortable: true,
    filterable: true,
    options: [
      { label: 'Equipment', value: 'equipment' },
      { label: 'Services', value: 'services' },
      { label: 'Talent', value: 'talent' },
      { label: 'Locations', value: 'locations' },
      { label: 'Materials', value: 'materials' },
      { label: 'Other', value: 'other' },
    ],
  },
  {
    key: 'status',
    label: 'Status',
    type: 'select',
    required: true,
    sortable: true,
    filterable: true,
    options: [
      { label: 'Draft', value: 'draft' },
      { label: 'Active', value: 'active' },
      { label: 'Archived', value: 'archived' },
    ],
  },
  {
    key: 'pricing.amount',
    label: 'Amount',
    type: 'currency',
    required: false,
    sortable: true,
    filterable: true,
  },
  {
    key: 'pricing.currency',
    label: 'Currency',
    type: 'text',
    required: false,
    sortable: true,
    filterable: true,
  },
  {
    key: 'location.city',
    label: 'City',
    type: 'text',
    required: false,
    sortable: true,
    filterable: true,
  },
  {
    key: 'location.country',
    label: 'Country',
    type: 'text',
    required: false,
    sortable: true,
    filterable: true,
  },
  {
    key: 'featured',
    label: 'Featured',
    type: 'boolean',
    required: false,
    sortable: true,
    filterable: true,
  },
  {
    key: 'response_count',
    label: 'Responses',
    type: 'number',
    required: false,
    sortable: true,
    filterable: true,
  },
  {
    key: 'created_at',
    label: 'Created',
    type: 'datetime',
    required: true,
    sortable: true,
    filterable: true,
  },
  {
    key: 'updated_at',
    label: 'Updated',
    type: 'datetime',
    required: true,
    sortable: true,
    filterable: true,
  },
];
