apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ghxstship-staging

bases:
  - ../../base

namePrefix: staging-

commonLabels:
  environment: staging

replicas:
  - name: ghxstship-web
    count: 2

patches:
  - patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/cpu
        value: 500m
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/memory
        value: 512Mi
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/cpu
        value: 1500m
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/memory
        value: 1536Mi
    target:
      kind: Deployment
      name: ghxstship-web

  - patch: |-
      - op: replace
        path: /spec/minReplicas
        value: 2
      - op: replace
        path: /spec/maxReplicas
        value: 8
    target:
      kind: HorizontalPodAutoscaler
      name: ghxstship-web

configMapGenerator:
  - name: ghxstship-config
    behavior: merge
    literals:
      - LOG_LEVEL=info
      - NODE_ENV=staging
