name: "Quality Issue Report"
description: "Report accessibility, performance, or UX quality issues"
title: "[QUALITY] "
labels: ["quality", "triage"]
body:
  - type: dropdown
    id: quality-dimension
    attributes:
      label: Quality Dimension
      description: Which quality area does this issue relate to?
      options:
        - Accessibility (WCAG Compliance)
        - Performance (Core Web Vitals)
        - Visual Consistency (Design System)
        - Interaction Resilience (Error Handling)
        - Cross-Platform Compatibility
        - Analytics & Monitoring
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: How critical is this issue?
      options:
        - Critical (Blocks users, legal compliance)
        - High (Major UX impact, performance degradation)
        - Medium (Noticeable UX friction, minor performance impact)
        - Low (Minor improvement opportunity)
    validations:
      required: true

  - type: input
    id: page-url
    attributes:
      label: Affected Page/URL
      description: Which page or component is affected?
      placeholder: "e.g., /products, /dashboard, MarketingCard component"
    validations:
      required: true

  - type: dropdown
    id: user-agent
    attributes:
      label: User Agent/Browser
      description: Which browser or device type is affected?
      options:
        - Chrome/Chromium
        - Firefox
        - Safari
        - Edge
        - Mobile Safari (iOS)
        - Chrome Mobile (Android)
        - All browsers
        - Unknown
    validations:
      required: false

  - type: textarea
    id: issue-description
    attributes:
      label: Issue Description
      description: Provide a clear, detailed description of the quality issue
      placeholder: "Describe what the issue is, how to reproduce it, and its impact on users"
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: What should happen instead?
      placeholder: "Describe the correct/expected behavior according to quality standards"
    validations:
      required: true

  - type: textarea
    id: reproduction-steps
    attributes:
      label: Steps to Reproduce
      description: How can this issue be reproduced?
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true

  - type: textarea
    id: technical-details
    attributes:
      label: Technical Details
      description: Any technical information that might help with fixing this issue
      placeholder: |
        - Browser console errors
        - Network request failures
        - Performance metrics
        - Accessibility testing tool results
        - Code snippets or component references
    validations:
      required: false

  - type: textarea
    id: impact-assessment
    attributes:
      label: Impact Assessment
      description: Assess the business and user impact of this issue
      placeholder: |
        **User Impact:** How does this affect users?
        **Business Impact:** Revenue, conversion, or retention impact?
        **Compliance:** Does this affect legal/regulatory compliance?
        **Scale:** How many users/pages are affected?
    validations:
      required: false

  - type: dropdown
    id: remediation-complexity
    attributes:
      label: Estimated Remediation Complexity
      description: How complex do you estimate fixing this issue will be?
      options:
        - Quick Fix (< 1 day)
        - Small Change (1-3 days)
        - Medium Effort (1-2 weeks)
        - Large Effort (1+ month)
        - Architectural Change
        - Unknown
    validations:
      required: false

  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed Solution
      description: If you have ideas for how to fix this issue, share them here
      placeholder: "Suggest implementation approaches, code changes, or design solutions"
    validations:
      required: false

  - type: checkboxes
    id: quality-checklist
    attributes:
      label: Quality Checklist
      description: Before submitting, please verify these quality standards
      options:
        - label: Issue follows established quality taxonomy
        - label: Impact assessment includes user and business considerations
        - label: Reproduction steps are clear and actionable
        - label: Technical details include relevant debugging information
        - label: Issue is not a duplicate of existing quality reports
