import { FieldConfig } from '@ghxstship/ui';

// Company field configurations
export const COMPANY_FIELD_CONFIGS: FieldConfig[] = [
  {
    key: 'name',
    label: 'Company Name',
    type: 'text',
    required: true,
    searchable: true,
    sortable: true,
    filterable: true,
    width: 200,
  },
  {
    key: 'industry',
    label: 'Industry',
    type: 'select',
    options: [
      { value: 'technology', label: 'Technology' },
      { value: 'finance', label: 'Finance' },
      { value: 'healthcare', label: 'Healthcare' },
      { value: 'manufacturing', label: 'Manufacturing' },
      { value: 'retail', label: 'Retail' },
      { value: 'construction', label: 'Construction' },
      { value: 'education', label: 'Education' },
      { value: 'entertainment', label: 'Entertainment' },
      { value: 'hospitality', label: 'Hospitality' },
      { value: 'transportation', label: 'Transportation' },
      { value: 'other', label: 'Other' },
    ],
    searchable: true,
    sortable: true,
    filterable: true,
    width: 150,
  },
  {
    key: 'status',
    label: 'Status',
    type: 'select',
    options: [
      { value: 'active', label: 'Active' },
      { value: 'pending', label: 'Pending' },
      { value: 'inactive', label: 'Inactive' },
      { value: 'blacklisted', label: 'Blacklisted' },
    ],
    required: true,
    sortable: true,
    filterable: true,
    width: 120,
  },
  {
    key: 'size',
    label: 'Company Size',
    type: 'select',
    options: [
      { value: 'startup', label: 'Startup (1-10)' },
      { value: 'small', label: 'Small (11-50)' },
      { value: 'medium', label: 'Medium (51-200)' },
      { value: 'large', label: 'Large (201-1000)' },
      { value: 'enterprise', label: 'Enterprise (1000+)' },
    ],
    sortable: true,
    filterable: true,
    width: 140,
  },
  {
    key: 'website',
    label: 'Website',
    type: 'url',
    searchable: true,
    sortable: true,
    width: 180,
  },
  {
    key: 'email',
    label: 'Email',
    type: 'email',
    searchable: true,
    sortable: true,
    width: 180,
  },
  {
    key: 'phone',
    label: 'Phone',
    type: 'phone',
    searchable: true,
    sortable: true,
    width: 140,
  },
  {
    key: 'city',
    label: 'City',
    type: 'text',
    searchable: true,
    sortable: true,
    filterable: true,
    width: 120,
  },
  {
    key: 'country',
    label: 'Country',
    type: 'text',
    searchable: true,
    sortable: true,
    filterable: true,
    width: 120,
  },
  {
    key: 'founded_year',
    label: 'Founded',
    type: 'number',
    sortable: true,
    filterable: true,
    width: 100,
  },
  {
    key: 'created_at',
    label: 'Created',
    type: 'datetime',
    sortable: true,
    filterable: true,
    width: 140,
  },
];

// Contract field configurations
export const CONTRACT_FIELD_CONFIGS: FieldConfig[] = [
  {
    key: 'title',
    label: 'Contract Title',
    type: 'text',
    required: true,
    searchable: true,
    sortable: true,
    width: 200,
  },
  {
    key: 'company_name',
    label: 'Company',
    type: 'text',
    searchable: true,
    sortable: true,
    filterable: true,
    width: 180,
  },
  {
    key: 'type',
    label: 'Type',
    type: 'select',
    options: [
      { value: 'msa', label: 'Master Service Agreement' },
      { value: 'sow', label: 'Statement of Work' },
      { value: 'nda', label: 'Non-Disclosure Agreement' },
      { value: 'service_agreement', label: 'Service Agreement' },
      { value: 'purchase_order', label: 'Purchase Order' },
      { value: 'other', label: 'Other' },
    ],
    required: true,
    sortable: true,
    filterable: true,
    width: 160,
  },
  {
    key: 'status',
    label: 'Status',
    type: 'select',
    options: [
      { value: 'draft', label: 'Draft' },
      { value: 'pending', label: 'Pending' },
      { value: 'active', label: 'Active' },
      { value: 'expired', label: 'Expired' },
      { value: 'terminated', label: 'Terminated' },
      { value: 'renewed', label: 'Renewed' },
    ],
    required: true,
    sortable: true,
    filterable: true,
    width: 120,
  },
  {
    key: 'value',
    label: 'Value',
    type: 'currency',
    sortable: true,
    filterable: true,
    width: 120,
  },
  {
    key: 'start_date',
    label: 'Start Date',
    type: 'date',
    sortable: true,
    filterable: true,
    width: 120,
  },
  {
    key: 'end_date',
    label: 'End Date',
    type: 'date',
    sortable: true,
    filterable: true,
    width: 120,
  },
  {
    key: 'auto_renew',
    label: 'Auto Renew',
    type: 'boolean',
    sortable: true,
    filterable: true,
    width: 100,
  },
  {
    key: 'created_at',
    label: 'Created',
    type: 'datetime',
    sortable: true,
    filterable: true,
    width: 140,
  },
];

// Qualification field configurations
export const QUALIFICATION_FIELD_CONFIGS: FieldConfig[] = [
  {
    key: 'name',
    label: 'Qualification Name',
    type: 'text',
    required: true,
    searchable: true,
    sortable: true,
    width: 200,
  },
  {
    key: 'company_name',
    label: 'Company',
    type: 'text',
    searchable: true,
    sortable: true,
    filterable: true,
    width: 180,
  },
  {
    key: 'type',
    label: 'Type',
    type: 'select',
    options: [
      { value: 'certification', label: 'Certification' },
      { value: 'license', label: 'License' },
      { value: 'insurance', label: 'Insurance' },
      { value: 'accreditation', label: 'Accreditation' },
      { value: 'compliance', label: 'Compliance' },
      { value: 'other', label: 'Other' },
    ],
    required: true,
    sortable: true,
    filterable: true,
    width: 140,
  },
  {
    key: 'verification_status',
    label: 'Status',
    type: 'select',
    options: [
      { value: 'pending', label: 'Pending' },
      { value: 'verified', label: 'Verified' },
      { value: 'expired', label: 'Expired' },
      { value: 'rejected', label: 'Rejected' },
    ],
    required: true,
    sortable: true,
    filterable: true,
    width: 120,
  },
  {
    key: 'issuing_authority',
    label: 'Issuing Authority',
    type: 'text',
    searchable: true,
    sortable: true,
    filterable: true,
    width: 160,
  },
  {
    key: 'certificate_number',
    label: 'Certificate #',
    type: 'text',
    searchable: true,
    sortable: true,
    width: 140,
  },
  {
    key: 'issue_date',
    label: 'Issue Date',
    type: 'date',
    sortable: true,
    filterable: true,
    width: 120,
  },
  {
    key: 'expiry_date',
    label: 'Expiry Date',
    type: 'date',
    sortable: true,
    filterable: true,
    width: 120,
  },
  {
    key: 'verification_date',
    label: 'Verified Date',
    type: 'date',
    sortable: true,
    filterable: true,
    width: 130,
  },
  {
    key: 'created_at',
    label: 'Created',
    type: 'datetime',
    sortable: true,
    filterable: true,
    width: 140,
  },
];

// Rating field configurations
export const RATING_FIELD_CONFIGS: FieldConfig[] = [
  {
    key: 'company_name',
    label: 'Company',
    type: 'text',
    searchable: true,
    sortable: true,
    filterable: true,
    width: 180,
  },
  {
    key: 'rating',
    label: 'Rating',
    type: 'number',
    required: true,
    sortable: true,
    filterable: true,
    width: 100,
  },
  {
    key: 'category',
    label: 'Category',
    type: 'select',
    options: [
      { value: 'overall', label: 'Overall' },
      { value: 'quality', label: 'Quality' },
      { value: 'timeliness', label: 'Timeliness' },
      { value: 'communication', label: 'Communication' },
      { value: 'value', label: 'Value' },
      { value: 'reliability', label: 'Reliability' },
    ],
    required: true,
    sortable: true,
    filterable: true,
    width: 140,
  },
  {
    key: 'recommendation',
    label: 'Recommendation',
    type: 'select',
    options: [
      { value: 'highly_recommended', label: 'Highly Recommended' },
      { value: 'recommended', label: 'Recommended' },
      { value: 'neutral', label: 'Neutral' },
      { value: 'not_recommended', label: 'Not Recommended' },
    ],
    required: true,
    sortable: true,
    filterable: true,
    width: 160,
  },
  {
    key: 'rater_name',
    label: 'Rated By',
    type: 'text',
    searchable: true,
    sortable: true,
    width: 140,
  },
  {
    key: 'review',
    label: 'Review',
    type: 'textarea',
    searchable: true,
    width: 200,
  },
  {
    key: 'is_public',
    label: 'Public',
    type: 'boolean',
    sortable: true,
    filterable: true,
    width: 80,
  },
  {
    key: 'created_at',
    label: 'Created',
    type: 'datetime',
    sortable: true,
    filterable: true,
    width: 140,
  },
];

// Contact field configurations
export const CONTACT_FIELD_CONFIGS: FieldConfig[] = [
  {
    key: 'first_name',
    label: 'First Name',
    type: 'text',
    required: true,
    searchable: true,
    sortable: true,
    width: 120,
  },
  {
    key: 'last_name',
    label: 'Last Name',
    type: 'text',
    required: true,
    searchable: true,
    sortable: true,
    width: 120,
  },
  {
    key: 'title',
    label: 'Title',
    type: 'text',
    searchable: true,
    sortable: true,
    width: 140,
  },
  {
    key: 'email',
    label: 'Email',
    type: 'email',
    searchable: true,
    sortable: true,
    width: 180,
  },
  {
    key: 'phone',
    label: 'Phone',
    type: 'phone',
    searchable: true,
    sortable: true,
    width: 140,
  },
  {
    key: 'department',
    label: 'Department',
    type: 'text',
    searchable: true,
    sortable: true,
    filterable: true,
    width: 140,
  },
  {
    key: 'is_primary',
    label: 'Primary',
    type: 'boolean',
    sortable: true,
    filterable: true,
    width: 80,
  },
  {
    key: 'created_at',
    label: 'Created',
    type: 'datetime',
    sortable: true,
    filterable: true,
    width: 140,
  },
];

// Export field mappings
export const EXPORT_FIELD_MAPPINGS = {
  companies: {
    name: 'Company Name',
    industry: 'Industry',
    status: 'Status',
    size: 'Company Size',
    website: 'Website',
    email: 'Email',
    phone: 'Phone',
    address: 'Address',
    city: 'City',
    state: 'State',
    country: 'Country',
    postal_code: 'Postal Code',
    founded_year: 'Founded Year',
    created_at: 'Created Date',
  },
  contracts: {
    title: 'Contract Title',
    company_name: 'Company',
    type: 'Contract Type',
    status: 'Status',
    value: 'Value',
    currency: 'Currency',
    start_date: 'Start Date',
    end_date: 'End Date',
    auto_renew: 'Auto Renew',
    created_at: 'Created Date',
  },
  qualifications: {
    name: 'Qualification Name',
    company_name: 'Company',
    type: 'Type',
    verification_status: 'Status',
    issuing_authority: 'Issuing Authority',
    certificate_number: 'Certificate Number',
    issue_date: 'Issue Date',
    expiry_date: 'Expiry Date',
    verification_date: 'Verification Date',
    created_at: 'Created Date',
  },
  ratings: {
    company_name: 'Company',
    rating: 'Rating',
    category: 'Category',
    recommendation: 'Recommendation',
    rater_name: 'Rated By',
    review: 'Review',
    is_public: 'Public',
    created_at: 'Created Date',
  },
};
