apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ghxstship

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - configmap.yaml
  - hpa.yaml
  - pdb.yaml

commonLabels:
  app.kubernetes.io/name: ghxstship
  app.kubernetes.io/managed-by: kustomize
