apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ghxstship-dev

bases:
  - ../../base

namePrefix: dev-

commonLabels:
  environment: dev

replicas:
  - name: ghxstship-web
    count: 1

patches:
  - patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/cpu
        value: 250m
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/memory
        value: 256Mi
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/cpu
        value: 1000m
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/memory
        value: 1Gi
    target:
      kind: Deployment
      name: ghxstship-web

  - patch: |-
      - op: replace
        path: /spec/minReplicas
        value: 1
      - op: replace
        path: /spec/maxReplicas
        value: 5
    target:
      kind: HorizontalPodAutoscaler
      name: ghxstship-web

configMapGenerator:
  - name: ghxstship-config
    behavior: merge
    literals:
      - LOG_LEVEL=debug
      - NODE_ENV=development
