name: PR Enterprise Validation

on:
  pull_request:
    branches: [ main, develop ]

jobs:
  enterprise-validation:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run Enterprise Compliance Audit
      run: |
        chmod +x ./scripts/enterprise-compliance-audit.sh
        ./scripts/enterprise-compliance-audit.sh
        
    - name: Run File Inventory Audit
      run: |
        chmod +x ./scripts/file-inventory-audit.sh
        ./scripts/file-inventory-audit.sh
        
    - name: TypeScript Check
      run: npx tsc --noEmit
      
    - name: ESLint Check
      run: npx eslint . --ext .ts,.tsx --max-warnings 0
      
    - name: Build Check
      run: npm run build
      
    - name: Test Suite
      run: npm test
      
    - name: Bundle Size Check
      run: |
        npm run build
        npx bundlesize
        
    - name: Security Audit
      run: npm audit --audit-level moderate
      
    - name: Upload Reports
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: compliance-reports
        path: reports/
