name: Repo Audit Enforcement

on:
  pull_request:
    branches: [ main, develop ]
  push:
    branches: [ main ]

jobs:
  repo-audit:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'pnpm'

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install deps
        run: pnpm install --frozen-lockfile

      - name: Run repo audit
        run: pnpm run audit:repo

      - name: Enforce thresholds
        run: node scripts/enforcement/enforce-repo-audit.js

      - name: Upload audit artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: repo-audit-artifacts
          path: |
            audit-deliverables/audit_report.json
            audit-deliverables/remediation_backlog.csv
            audit-deliverables/file_tree_blueprint.md
