name: Validate Design Tokens

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  validate-tokens:
    name: Design Token Validation
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          
      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT
          
      - name: Setup pnpm cache
        uses: actions/cache@v3
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-
            
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
        
      - name: Validate design tokens
        run: |
          cd packages/ui
          pnpm validate:tokens:ci
        continue-on-error: false
        
      - name: Lint with token rules
        run: |
          cd packages/ui
          pnpm lint:tokens:ci
        continue-on-error: false
        
      - name: Check for hardcoded colors
        run: |
          echo "🔍 Scanning for hardcoded color values..."
          
          # Check for hex colors (excluding allowed patterns)
          HEX_COLORS=$(grep -r --include="*.tsx" --include="*.ts" --include="*.jsx" --include="*.js" \
            --exclude-dir=node_modules --exclude-dir=.next --exclude-dir=dist --exclude-dir=build \
            -E '#[0-9a-fA-F]{3,6}' apps/web packages/ui || true)
          
          if [ ! -z "$HEX_COLORS" ]; then
            echo "❌ Hardcoded hex colors found:"
            echo "$HEX_COLORS"
            exit 1
          fi
          
          # Check for RGB/RGBA values
          RGB_COLORS=$(grep -r --include="*.tsx" --include="*.ts" --include="*.jsx" --include="*.js" \
            --exclude-dir=node_modules --exclude-dir=.next --exclude-dir=dist --exclude-dir=build \
            -E 'rgba?\([0-9]' apps/web packages/ui || true)
          
          if [ ! -z "$RGB_COLORS" ]; then
            echo "❌ Hardcoded RGB/RGBA colors found:"
            echo "$RGB_COLORS"
            exit 1
          fi
          
          echo "✅ No hardcoded colors found!"
          
      - name: Generate token report
        if: always()
        run: |
          cd packages/ui
          pnpm validate:tokens > token-report.txt || true
          
      - name: Upload token report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: token-validation-report
          path: packages/ui/token-report.txt
          
      - name: Comment PR with results
        if: github.event_name == 'pull_request' && failure()
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '❌ **Design Token Validation Failed**\n\nHardcoded color values detected. Please use semantic tokens instead.\n\nSee the [token validation report](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}) for details.\n\n**Quick Fix:**\n```bash\npnpm fix:colors\npnpm validate:tokens\n```'
            })
